### ISSUE TITLE
Taalgebruik

### ISSUE THREAD

**Issue by thombrink** [SnelStartSoftware/B2B.client.net#13]
Wie heeft er bedacht om Nederlands en Engels door elkaar heen te gaan gebruiken?

**Comment by henrybeensnelstart** [comment]
Wij schrijven programmacode in principe in het Engels, maar maken daarbinnen voor terminologie wel gebruik van het Nederlands. Onze ervaring is dat dat beter werkt voor domeinterminologie, omdat de betekenis van termen dan preciezer begrepen wordt. Dit is een SnelStart brede keuze, die we doorgetrokken hebben naar deze client.

Daarnaast hebben we er voor gekozen om alle documentatie rondom deze client in het Engels te doen, dit omdat we merken dat er relatief veel mensen bij onze partners werken die alleen Engels spreken.

Communicatie met partners doen we in de taal die de partner prefereert.
