### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by thombrink** [SnelStartSoftware/B2B.client.net#17]
Zijn jullie van plan in de toekomst deze source via een nuget package beschikbaar te maken? Dat is wat handiger dan zelf de code bij houden.

**Comment by henrybeen** [comment]
De code is al enige tijd via NuGet beschikbaar (staat ook onderaan de Readme) en wel hier: https://www.nuget.org/packages/SnelStart.B2B.Client/
