### ISSUE TITLE
VerkoopboekingBijlagesOperations is not available in the B2BClient

### ISSUE THREAD

**Issue by thombrink** [SnelStartSoftware/B2B.client.net#23]

**Comment by floris85** [comment]
currently working on this!

**Comment by thombrink** [comment]
Thanks for the notice. I almost started working on this myself.

**Comment by thombrink** [comment]
Do you have an ETA?

**Comment by floris85** [comment]
hopefully today, i'll make a pull request today so we could work together on this if necessary.
