### ISSUE TITLE
Verkoopfactuur vervaldatum nullable?

### ISSUE THREAD

**Issue by floris85** [SnelStartSoftware/B2B.client.net#34]
Hi guys,

We got an error earlier when retrieving a list of verkoopfacturen.
The task crashed because the 'vervaldatum' was NULL, while in the model it isn't nullable.
Is this supposed to happen? Should we then change the model?

Hope to hear from you!

Regards,
Floris

**Comment by tvandegraaf** [comment]
Hi Floris,

Thank you for opening an issue on our tracker.

I just checked to see if the "vervaldatum" should be nullable and you are right, the model in the client is wrong. I will resolve this issue soon.

Tom

**Comment by floris85** [comment]
Thanks @tvandegraaf, I'll grab the latest version and update it in our solution!

**Comment by tvandegraaf** [comment]
No problem @floris85 !
Just pushed a fix to NuGet. It might take a few minutes to show up between the updates.

I am closing this issue now.
