### ISSUE TITLE
Property types komen niet overeen

### ISSUE THREAD

**Issue by thombrink** [SnelStartSoftware/B2B.client.net#37]
De api accepteert doubles bij de bedragen van een verkoopboeking, maar in deze library worden decimals gebruikt.

(als ik tijd heb voeg ik zometeen nog even een voorbeeld toe)

**Comment by tvandegraaf** [comment]
In de implementatie van de B2B API met betrekking tot verkoopboekingen zie ik dat er gebruik wordt gemaakt van decimals. De client heeft dan ook de juiste property types.

Zou je een voorbeeld kunnen toevoegen om het issue te verduidelijken?

**Comment by thombrink** [comment]
Onderstaand de voorbeelden van het api specificatie:

Het factuurbedrag:
```
"factuurbedrag": {
  "format": "double",
  "description": "Het factuurbedrag van de verkoopboeking.",
  "type": "number"
},
```

Boekingsregelbedrag:
```
"bedrag": {
  "format": "double",
  "description": "Het omzetbedrag van de regel, exclusief btw.",
  "type": "number"
},
```

Btwregelbedrag:
```
"btwBedrag": {
  "format": "double",
  "description": "Het btw-bedrag dat voor de gegeven btwsoort wordt geboekt.",
  "type": "number"
}
```

https://b2bapi-developer.snelstart.nl/docs/services/57bb00f34a3a8710c85ed7dc/operations/5a7320d10b026313f4695030?

**Comment by tvandegraaf** [comment]
Ik snap nu wat je bedoelt.

De documentatie die wij hebben voor de B2B API is gespecificeerd om niet taalspecifiek te zijn. Een `decimal` is programmeertaal-specifiek, vandaar dat er voor de `format` property gekozen wordt voor `double`. Dit wordt gedaan met de [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) in gedachten.

Dit houdt niet in dat je geen `decimal` kunt gebruiken. Wat je uiteindelijk over de lijn stuurt zal een `number` zijn die wordt geparsed als een `decimal`.
